# Flowable 流程引擎專用配置
# 此配置檔案包含 Flowable 引擎的詳細設定參數
# Flowable 引擎配置
flowable:
  database-schema-update: true
  # Flowable會去掃DB的表，如果已經存在就不建立，若有多個db user時，需要指定schema(但目前實測此參數無效
  database-schema: FLOWTESTDB
  async-executor-activate: true
  # 歷史資料配置
  history-level: full

  # IDM 身份管理配置
  idm:
    enabled: true
    password-encoder: spring_delegating_noop
    ldap:
      enabled: false

  # REST API 配置
  rest-api-enabled: false
