# Spring
spring:
  application:
    name: flowable
  profiles:
    include: eureka,actuator,info,flowable,undertow
  config:
    import: adapter.yml
  # DataSource
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/ORCLCDB
    username: FLOWTESTDB
    password: flowtest123
    driver-class-name: oracle.jdbc.OracleDriver

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8081
  servlet:
    encoding:
      enabled: false
