# Spring
spring:
  application:
    name: fsap-flowable
  profiles:
    active: @spring.active.profiles@
    include: eureka,actuator,flowable
  # DataSource
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/ORCLCDB
    username: FLOWTESTDB
    password: flowtest123
    driver-class-name: oracle.jdbc.OracleDriver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8081
  servlet:
    encoding:
      enabled: false
